export const COUNTRIES = [
  { gl: "af", country: "Afghanistan" },
  { gl: "al", country: "Albania" },
  { gl: "dz", country: "Algeria" },
  { gl: "as", country: "American Samoa" },
  { gl: "ad", country: "Andorra" },
  { gl: "ao", country: "Angola" },
  { gl: "ai", country: "Anguilla" },
  { gl: "aq", country: "Antarctica" },
  { gl: "ag", country: "Antigua and Barbuda" },
  { gl: "ar", country: "Argentina" },
  { gl: "am", country: "Armenia" },
  { gl: "aw", country: "Aruba" },
  { gl: "au", country: "Australia" },
  { gl: "at", country: "Austria" },
  { gl: "az", country: "Azerbaijan" },
  { gl: "bs", country: "Bahamas" },
  { gl: "bh", country: "Bahrain" },
  { gl: "bd", country: "Bangladesh" },
  { gl: "bb", country: "Barbados" },
  { gl: "by", country: "Belarus" },
  { gl: "be", country: "Belgium" },
  { gl: "bz", country: "Belize" },
  { gl: "bj", country: "Benin" },
  { gl: "bm", country: "Bermuda" },
  { gl: "bt", country: "Bhutan" },
  { gl: "bo", country: "Bolivia" },
  { gl: "ba", country: "Bosnia and Herzegovina" },
  { gl: "bw", country: "Botswana" },
  { gl: "bv", country: "Bouvet Island" },
  { gl: "br", country: "Brazil" },
  { gl: "io", country: "British Indian Ocean Territory" },
  { gl: "bn", country: "Brunei Darussalam" },
  { gl: "bg", country: "Bulgaria" },
  { gl: "bf", country: "Burkina Faso" },
  { gl: "bi", country: "Burundi" },
  { gl: "kh", country: "Cambodia" },
  { gl: "cm", country: "Cameroon" },
  { gl: "ca", country: "Canada" },
  { gl: "cv", country: "Cape Verde" },
  { gl: "ky", country: "Cayman Islands" },
  { gl: "cf", country: "Central African Republic" },
  { gl: "td", country: "Chad" },
  { gl: "cl", country: "Chile" },
  { gl: "cn", country: "China" },
  { gl: "cx", country: "Christmas Island" },
  { gl: "cc", country: "Cocos (Keeling) Islands" },
  { gl: "co", country: "Colombia" },
  { gl: "km", country: "Comoros" },
  { gl: "cg", country: "Congo" },
  { gl: "cd", country: "Congo, the Democratic Republic of the" },
  { gl: "ck", country: "Cook Islands" },
  { gl: "cr", country: "Costa Rica" },
  { gl: "ci", country: "Cote D'ivoire" },
  { gl: "hr", country: "Croatia" },
  { gl: "cu", country: "Cuba" },
  { gl: "cy", country: "Cyprus" },
  { gl: "cz", country: "Czech Republic" },
  { gl: "dk", country: "Denmark" },
  { gl: "dj", country: "Djibouti" },
  { gl: "dm", country: "Dominica" },
  { gl: "do", country: "Dominican Republic" },
  { gl: "ec", country: "Ecuador" },
  { gl: "eg", country: "Egypt" },
  { gl: "sv", country: "El Salvador" },
  { gl: "gq", country: "Equatorial Guinea" },
  { gl: "er", country: "Eritrea" },
  { gl: "ee", country: "Estonia" },
  { gl: "et", country: "Ethiopia" },
  { gl: "fk", country: "Falkland Islands (Malvinas)" },
  { gl: "fo", country: "Faroe Islands" },
  { gl: "fj", country: "Fiji" },
  { gl: "fi", country: "Finland" },
  { gl: "fr", country: "France" },
  { gl: "gf", country: "French Guiana" },
  { gl: "pf", country: "French Polynesia" },
  { gl: "tf", country: "French Southern Territories" },
  { gl: "ga", country: "Gabon" },
  { gl: "gm", country: "Gambia" },
  { gl: "ge", country: "Georgia" },
  { gl: "de", country: "Germany" },
  { gl: "gh", country: "Ghana" },
  { gl: "gi", country: "Gibraltar" },
  { gl: "gr", country: "Greece" },
  { gl: "gl", country: "Greenland" },
  { gl: "gd", country: "Grenada" },
  { gl: "gp", country: "Guadeloupe" },
  { gl: "gu", country: "Guam" },
  { gl: "gt", country: "Guatemala" },
  { gl: "gg", country: "Guernsey" },
  { gl: "gn", country: "Guinea" },
  { gl: "gw", country: "Guinea-Bissau" },
  { gl: "gy", country: "Guyana" },
  { gl: "ht", country: "Haiti" },
  { gl: "hm", country: "Heard Island and Mcdonald Islands" },
  { gl: "va", country: "Holy See (Vatican City State)" },
  { gl: "hn", country: "Honduras" },
  { gl: "hk", country: "Hong Kong" },
  { gl: "hu", country: "Hungary" },
  { gl: "is", country: "Iceland" },
  { gl: "in", country: "India" },
  { gl: "id", country: "Indonesia" },
  { gl: "ir", country: "Iran, Islamic Republic of" },
  { gl: "iq", country: "Iraq" },
  { gl: "ie", country: "Ireland" },
  { gl: "im", country: "Isle of Man" },
  { gl: "il", country: "Israel" },
  { gl: "it", country: "Italy" },
  { gl: "je", country: "Jersey" },
  { gl: "jm", country: "Jamaica" },
  { gl: "jp", country: "Japan" },
  { gl: "jo", country: "Jordan" },
  { gl: "kz", country: "Kazakhstan" },
  { gl: "ke", country: "Kenya" },
  { gl: "ki", country: "Kiribati" },
  { gl: "kp", country: "Korea, Democratic People's Republic of" },
  { gl: "kr", country: "Korea, Republic of" },
  { gl: "kw", country: "Kuwait" },
  { gl: "kg", country: "Kyrgyzstan" },
  { gl: "la", country: "Lao People's Democratic Republic" },
  { gl: "lv", country: "Latvia" },
  { gl: "lb", country: "Lebanon" },
  { gl: "ls", country: "Lesotho" },
  { gl: "lr", country: "Liberia" },
  { gl: "ly", country: "Libyan Arab Jamahiriya" },
  { gl: "li", country: "Liechtenstein" },
  { gl: "lt", country: "Lithuania" },
  { gl: "lu", country: "Luxembourg" },
  { gl: "mo", country: "Macao" },
  { gl: "mk", country: "Macedonia, the Former Yugosalv Republic of" },
  { gl: "mg", country: "Madagascar" },
  { gl: "mw", country: "Malawi" },
  { gl: "my", country: "Malaysia" },
  { gl: "mv", country: "Maldives" },
  { gl: "ml", country: "Mali" },
  { gl: "mt", country: "Malta" },
  { gl: "mh", country: "Marshall Islands" },
  { gl: "mq", country: "Martinique" },
  { gl: "mr", country: "Mauritania" },
  { gl: "mu", country: "Mauritius" },
  { gl: "yt", country: "Mayotte" },
  { gl: "mx", country: "Mexico" },
  { gl: "fm", country: "Micronesia, Federated States of" },
  { gl: "md", country: "Moldova, Republic of" },
  { gl: "mc", country: "Monaco" },
  { gl: "mn", country: "Mongolia" },
  { gl: "me", country: "Montenegro" },
  { gl: "ms", country: "Montserrat" },
  { gl: "ma", country: "Morocco" },
  { gl: "mz", country: "Mozambique" },
  { gl: "mm", country: "Myanmar" },
  { gl: "na", country: "Namibia" },
  { gl: "nr", country: "Nauru" },
  { gl: "np", country: "Nepal" },
  { gl: "nl", country: "Netherlands" },
  { gl: "an", country: "Netherlands Antilles" },
  { gl: "nc", country: "New Caledonia" },
  { gl: "nz", country: "New Zealand" },
  { gl: "ni", country: "Nicaragua" },
  { gl: "ne", country: "Niger" },
  { gl: "ng", country: "Nigeria" },
  { gl: "nu", country: "Niue" },
  { gl: "nf", country: "Norfolk Island" },
  { gl: "mp", country: "Northern Mariana Islands" },
  { gl: "no", country: "Norway" },
  { gl: "om", country: "Oman" },
  { gl: "pk", country: "Pakistan" },
  { gl: "pw", country: "Palau" },
  { gl: "ps", country: "Palestinian Territory, Occupied" },
  { gl: "pa", country: "Panama" },
  { gl: "pg", country: "Papua New Guinea" },
  { gl: "py", country: "Paraguay" },
  { gl: "pe", country: "Peru" },
  { gl: "ph", country: "Philippines" },
  { gl: "pn", country: "Pitcairn" },
  { gl: "pl", country: "Poland" },
  { gl: "pt", country: "Portugal" },
  { gl: "pr", country: "Puerto Rico" },
  { gl: "qa", country: "Qatar" },
  { gl: "re", country: "Reunion" },
  { gl: "ro", country: "Romania" },
  { gl: "ru", country: "Russian Federation" },
  { gl: "rw", country: "Rwanda" },
  { gl: "sh", country: "Saint Helena" },
  { gl: "kn", country: "Saint Kitts and Nevis" },
  { gl: "lc", country: "Saint Lucia" },
  { gl: "pm", country: "Saint Pierre and Miquelon" },
  { gl: "vc", country: "Saint Vincent and the Grenadines" },
  { gl: "ws", country: "Samoa" },
  { gl: "sm", country: "San Marino" },
  { gl: "st", country: "Sao Tome and Principe" },
  { gl: "sa", country: "Saudi Arabia" },
  { gl: "sn", country: "Senegal" },
  { gl: "rs", country: "Serbia" },
  { gl: "sc", country: "Seychelles" },
  { gl: "sl", country: "Sierra Leone" },
  { gl: "sg", country: "Singapore" },
  { gl: "sk", country: "Slovakia" },
  { gl: "si", country: "Slovenia" },
  { gl: "sb", country: "Solomon Islands" },
  { gl: "so", country: "Somalia" },
  { gl: "za", country: "South Africa" },
  { gl: "gs", country: "South Georgia and the South Sandwich Islands" },
  { gl: "es", country: "Spain" },
  { gl: "lk", country: "Sri Lanka" },
  { gl: "sd", country: "Sudan" },
  { gl: "sr", country: "Suriname" },
  { gl: "sj", country: "Svalbard and Jan Mayen" },
  { gl: "sz", country: "Swaziland" },
  { gl: "se", country: "Sweden" },
  { gl: "ch", country: "Switzerland" },
  { gl: "sy", country: "Syrian Arab Republic" },
  { gl: "tw", country: "Taiwan, Province of China" },
  { gl: "tj", country: "Tajikistan" },
  { gl: "tz", country: "Tanzania, United Republic of" },
  { gl: "th", country: "Thailand" },
  { gl: "tl", country: "Timor-Leste" },
  { gl: "tg", country: "Togo" },
  { gl: "tk", country: "Tokelau" },
  { gl: "to", country: "Tonga" },
  { gl: "tt", country: "Trinidad and Tobago" },
  { gl: "tn", country: "Tunisia" },
  { gl: "tr", country: "Turkiye" },
  { gl: "tm", country: "Turkmenistan" },
  { gl: "tc", country: "Turks and Caicos Islands" },
  { gl: "tv", country: "Tuvalu" },
  { gl: "ug", country: "Uganda" },
  { gl: "ua", country: "Ukraine" },
  { gl: "ae", country: "United Arab Emirates" },
  { gl: "uk", country: "United Kingdom" },
  { gl: "gb", country: "United Kingdom" },
  { gl: "us", country: "United States" },
  { gl: "um", country: "United States Minor Outlying Islands" },
  { gl: "uy", country: "Uruguay" },
  { gl: "uz", country: "Uzbekistan" },
  { gl: "vu", country: "Vanuatu" },
  { gl: "ve", country: "Venezuela" },
  { gl: "vn", country: "Viet Nam" },
  { gl: "vg", country: "Virgin Islands, British" },
  { gl: "vi", country: "Virgin Islands, U.S." },
  { gl: "wf", country: "Wallis and Futuna" },
  { gl: "eh", country: "Western Sahara" },
  { gl: "ye", country: "Yemen" },
  { gl: "zm", country: "Zambia" },
  { gl: "zw", country: "Zimbabwe" },
];
