export const LANGUAGES = [
  { hl: "ab", language: "Abkhazian" },
  { hl: "aa", language: "Afar" },
  { hl: "af", language: "Afrikaans" },
  { hl: "ak", language: "Akan" },
  { hl: "sq", language: "Albanian" },
  { hl: "am", language: "Amharic" },
  { hl: "ar", language: "Arabic" },
  { hl: "an", language: "Aragonese" },
  { hl: "hy", language: "Armenian" },
  { hl: "as", language: "Assamese" },
  { hl: "av", language: "Avaric" },
  { hl: "ae", language: "Avestan" },
  { hl: "ay", language: "Aymara" },
  { hl: "az", language: "Azerbaijani" },
  { hl: "bm", language: "Bambara" },
  { hl: "ba", language: "Bashkir" },
  { hl: "eu", language: "Basque" },
  { hl: "be", language: "Belarusian" },
  { hl: "bn", language: "Bengali (Bangla)" },
  { hl: "bh", language: "Bihari" },
  { hl: "bi", language: "Bislama" },
  { hl: "bs", language: "Bosnian" },
  { hl: "br", language: "Breton" },
  { hl: "bg", language: "Bulgarian" },
  { hl: "my", language: "Burmese" },
  { hl: "ca", language: "Catalan" },
  { hl: "ch", language: "Chamorro" },
  { hl: "ce", language: "Chechen" },
  { hl: "ny", language: "Chichewa, Chewa, Nyanja" },
  { hl: "zh", language: "Chinese" },
  { hl: "zh-Hans", language: "Chinese (Simplified)" },
  { hl: "zh-Hant", language: "Chinese (Traditional)" },
  { hl: "cv", language: "Chuvash" },
  { hl: "kw", language: "Cornish" },
  { hl: "co", language: "Corsican" },
  { hl: "cr", language: "Cree" },
  { hl: "hr", language: "Croatian" },
  { hl: "cs", language: "Czech" },
  { hl: "da", language: "Danish" },
  { hl: "dv", language: "Divehi, Dhivehi, Maldivian" },
  { hl: "nl", language: "Dutch" },
  { hl: "dz", language: "Dzongkha" },
  { hl: "en", language: "English" },
  { hl: "eo", language: "Esperanto" },
  { hl: "et", language: "Estonian" },
  { hl: "ee", language: "Ewe" },
  { hl: "fo", language: "Faroese" },
  { hl: "fj", language: "Fijian" },
  { hl: "fi", language: "Finnish" },
  { hl: "fr", language: "French" },
  { hl: "ff", language: "Fula, Fulah, Pulaar, Pular" },
  { hl: "gl", language: "Galician" },
  { hl: "gd", language: "Gaelic (Scottish)" },
  { hl: "gv", language: "Gaelic (Manx)" },
  { hl: "ka", language: "Georgian" },
  { hl: "de", language: "German" },
  { hl: "el", language: "Greek" },
  { hl: "kl", language: "Greenlandic" },
  { hl: "gn", language: "Guarani" },
  { hl: "gu", language: "Gujarati" },
  { hl: "ht", language: "Haitian Creole" },
  { hl: "ha", language: "Hausa" },
  { hl: "he", language: "Hebrew" },
  { hl: "hz", language: "Herero" },
  { hl: "hi", language: "Hindi" },
  { hl: "ho", language: "Hiri Motu" },
  { hl: "hu", language: "Hungarian" },
  { hl: "is", language: "Icelandic" },
  { hl: "io", language: "Ido" },
  { hl: "ig", language: "Igbo" },
  { hl: "id", language: "Indonesian" },
  { hl: "ia", language: "Interlingua" },
  { hl: "ie", language: "Interlingue" },
  { hl: "iu", language: "Inuktitut" },
  { hl: "ik", language: "Inupiak" },
  { hl: "ga", language: "Irish" },
  { hl: "it", language: "Italian" },
  { hl: "ja", language: "Japanese" },
  { hl: "jv", language: "Javanese" },
  { hl: "kn", language: "Kannada" },
  { hl: "kr", language: "Kanuri" },
  { hl: "ks", language: "Kashmiri" },
  { hl: "kk", language: "Kazakh" },
  { hl: "km", language: "Khmer" },
  { hl: "ki", language: "Kikuyu" },
  { hl: "rw", language: "Kinyarwanda (Rwanda)" },
  { hl: "rn", language: "Kirundi" },
  { hl: "ky", language: "Kyrgyz" },
  { hl: "kv", language: "Komi" },
  { hl: "kg", language: "Kongo" },
  { hl: "ko", language: "Korean" },
  { hl: "ku", language: "Kurdish" },
  { hl: "kj", language: "Kwanyama" },
  { hl: "lo", language: "Lao" },
  { hl: "la", language: "Latin" },
  { hl: "lv", language: "Latvian (Lettish)" },
  { hl: "li", language: "Limburgish ( Limburger)" },
  { hl: "ln", language: "Lingala" },
  { hl: "lt", language: "Lithuanian" },
  { hl: "lu", language: "Luga-Katanga" },
  { hl: "lg", language: "Luganda, Ganda" },
  { hl: "lb", language: "Luxembourgish" },
  { hl: "mk", language: "Macedonian" },
  { hl: "mg", language: "Malagasy" },
  { hl: "ms", language: "Malay" },
  { hl: "ml", language: "Malayalam" },
  { hl: "mt", language: "Maltese" },
  { hl: "mi", language: "Maori" },
  { hl: "mr", language: "Marathi" },
  { hl: "mh", language: "Marshallese" },
  { hl: "mo", language: "Moldavian" },
  { hl: "mn", language: "Mongolian" },
  { hl: "na", language: "Nauru" },
  { hl: "nv", language: "Navajo" },
  { hl: "ng", language: "Ndonga" },
  { hl: "nd", language: "Northern Ndebele" },
  { hl: "ne", language: "Nepali" },
  { hl: "no", language: "Norwegian" },
  { hl: "nb", language: "Norwegian bokmål" },
  { hl: "nn", language: "Norwegian nynorsk" },
  { hl: "ii", language: "Nuosu" },
  { hl: "oc", language: "Occitan" },
  { hl: "oj", language: "Ojibwe" },
  { hl: "cu", language: "Old Church Slavonic, Old Bulgarian" },
  { hl: "or", language: "Oriya" },
  { hl: "om", language: "Oromo (Afaan Oromo)" },
  { hl: "os", language: "Ossetian" },
  { hl: "pi", language: "Pāli" },
  { hl: "ps", language: "Pashto, Pushto" },
  { hl: "fa", language: "Persian (Farsi)" },
  { hl: "pl", language: "Polish" },
  { hl: "pt", language: "Portuguese" },
  { hl: "pa", language: "Punjabi (Eastern)" },
  { hl: "qu", language: "Quechua" },
  { hl: "rm", language: "Romansh" },
  { hl: "ro", language: "Romanian" },
  { hl: "ru", language: "Russian" },
  { hl: "se", language: "Sami" },
  { hl: "sm", language: "Samoan" },
  { hl: "sg", language: "Sango" },
  { hl: "sa", language: "Sanskrit" },
  { hl: "sr", language: "Serbian" },
  { hl: "sh", language: "Serbo-Croatian" },
  { hl: "st", language: "Sesotho" },
  { hl: "tn", language: "Setswana" },
  { hl: "sn", language: "Shona" },
  { hl: "sd", language: "Sindhi" },
  { hl: "si", language: "Sinhalese" },
  { hl: "ss", language: "Siswati" },
  { hl: "sk", language: "Slovak" },
  { hl: "sl", language: "Slovenian" },
  { hl: "so", language: "Somali" },
  { hl: "nr", language: "Southern Ndebele" },
  { hl: "es", language: "Spanish" },
  { hl: "su", language: "Sundanese" },
  { hl: "sw", language: "Swahili (Kiswahili)" },
  { hl: "sv", language: "Swedish" },
  { hl: "tl", language: "Tagalog" },
  { hl: "ty", language: "Tahitian" },
  { hl: "tg", language: "Tajik" },
  { hl: "ta", language: "Tamil" },
  { hl: "tt", language: "Tatar" },
  { hl: "te", language: "Telugu" },
  { hl: "th", language: "Thai" },
  { hl: "bo", language: "Tibetan" },
  { hl: "ti", language: "Tigrinya" },
  { hl: "to", language: "Tonga" },
  { hl: "ts", language: "Tsonga" },
  { hl: "tr", language: "Turkish" },
  { hl: "tk", language: "Turkmen" },
  { hl: "tw", language: "Twi" },
  { hl: "ug", language: "Uyghur" },
  { hl: "uk", language: "Ukrainian" },
  { hl: "ur", language: "Urdu" },
  { hl: "uz", language: "Uzbek" },
  { hl: "ve", language: "Venda" },
  { hl: "vi", language: "Vietnamese" },
  { hl: "vo", language: "Volapük" },
  { hl: "wa", language: "Wallon" },
  { hl: "cy", language: "Welsh" },
  { hl: "wo", language: "Wolof" },
  { hl: "fy", language: "Western Frisian" },
  { hl: "xh", language: "Xhosa" },
  { hl: "yi", language: "Yiddish" },
  { hl: "yo", language: "Yoruba" },
  { hl: "za", language: "Zhuang, Chuang" },
  { hl: "zu", language: "Zulu" },
];
